### ISSUE TITLE
Binary name conflict with lrzsz

### ISSUE THREAD

**Issue by Seirdy** [v-byte-cpu/sx#98]
[lrzsz](http://www.ohse.de/uwe/software/lrzsz.html) (used by software like [minicom](https://en.wikipedia.org/wiki/Minicom) and other rzsz-based software offer the `sx` executable for sending files with the XMODEM protocol.

Modems aren't used that much anymore, so this probably isn't a showstopper; minicom is mostly useful for working with remote computers over a broken LAN nowadays. However, it might be worth knowing that another existing networking-related utility shares this tool's name.

**Comment by v-byte-cpu** [comment]
Hi @Seirdy ! Thank you for pointing out the existence of such a utility, I didn't know about it. Based on the latest release date `Version 0.12.20 - December 1998, Uwe Ohse`, it looks like it has been abandoned. I am also aware of the existence of another utility with the same name https://github.com/Earnestly/sx. But I don't think it is necessary to rename an application just because someone gave it the same name to another product before. Moreover, nowadays it is difficult to avoid the collision of names. Nevertheless it is an interesting fact, thank you again.
